// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIMgESV-ase_ZEpGON1K0xHWQAtS4r3RQ',
    appId: '1:953111851263:android:72de749517ceb2085c5cca',
    messagingSenderId: '953111851263',
    projectId: 'cmsc4513-bmw-capstone',
    storageBucket: 'cmsc4513-bmw-capstone.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTzHwVE-NtsqRa_rtAlLZr-ioaz2155lo',
    appId: '1:953111851263:ios:4d40152cd7ed2b185c5cca',
    messagingSenderId: '953111851263',
    projectId: 'cmsc4513-bmw-capstone',
    storageBucket: 'cmsc4513-bmw-capstone.appspot.com',
    androidClientId: '953111851263-olt8mu995t9cvscbrt0ani24a43d8c44.apps.googleusercontent.com',
    iosClientId: '953111851263-3mamha7f61fmf70sb765pq873b0ge220.apps.googleusercontent.com',
    iosBundleId: 'com.example.capProject',
  );
}
